// Run against a throwaway demo database: BASE_URL=http://127.0.0.1:8000 node tests/browser-smoke.cjs
// Requires Playwright and its Chromium browser; this exercises real UI mutations.
const assert = require('node:assert/strict');
const {chromium} = require('playwright');
const path = require('node:path');
const artifactDir = path.join(require('node:os').tmpdir(),'axiom-qa');
require('node:fs').mkdirSync(artifactDir,{recursive:true});
(async()=>{
  let options={headless:true};
  if(process.env.CHROMIUM_PATH) options={...options,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']};
  const browser=await chromium.launch(options);
  const page=await browser.newPage({viewport:{width:1440,height:1100}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.BASE_URL||'http://127.0.0.1:8000');
  await page.getByRole('heading',{name:'Market intelligence, in motion.'}).waitFor();
  await page.screenshot({path:path.join(artifactDir,'overview.png'),fullPage:true});
  await page.getByRole('button',{name:'Run pipeline'}).click();
  await page.locator('#toast').filter({hasText:'Pipeline complete'}).waitFor();
  await page.locator('nav').getByRole('button',{name:'Intelligence'}).click();
  await page.locator('#search').fill('AAPL');
  assert(await page.locator('#filtered-events .event-row').count()>0);
  await page.locator('#filtered-events .event-title').first().click();
  await page.locator('dialog[open]').waitFor();
  await page.getByRole('button',{name:'Close',exact:true}).click();
  // Choose an unfilled BUY signal from the loaded state rather than guessing row order.
  const state=await page.evaluate(()=>fetch('/api/v1/workbench/state').then(r=>r.json()));
  const buy=state.signals.find(s=>s.action==='BUY'&&s.status==='pending'&&Date.now()/1000-s.created<86400);
  assert(buy,'expected a fresh demo BUY signal');
  await page.locator(`[data-execute="${buy.id}"]`).click();
  await page.getByLabel('Whole shares (optional)').fill('2');
  await page.getByRole('button',{name:'Submit paper order'}).click();
  await page.locator('#toast').filter({hasText:'Paper fill'}).waitFor();
  await page.locator('nav').getByRole('button',{name:'Paper portfolio'}).click();
  await page.getByRole('heading',{name:'Open positions'}).waitFor();
  await page.screenshot({path:path.join(artifactDir,'portfolio.png'),fullPage:true});
  await page.getByRole('button',{name:'Pause execution'}).click();
  await page.getByRole('button',{name:'Resume execution'}).waitFor();
  await page.getByRole('button',{name:'Resume execution'}).click();
  await page.locator('nav').getByRole('button',{name:'Model lab'}).click();
  await page.getByRole('button',{name:'Train & evaluate'}).click();
  await page.locator('#toast').filter({hasText:'Evaluation complete'}).waitFor({timeout:30000});
  await page.getByRole('button',{name:'Activate for future events'}).click();
  await page.locator('#toast').filter({hasText:'Prediction policy updated'}).waitFor();
  await page.screenshot({path:path.join(artifactDir,'models.png'),fullPage:true});
  await page.getByRole('button',{name:'Return to keyword baseline'}).click();
  await page.locator('nav').getByRole('button',{name:'Settings'}).click();
  await page.getByLabel('Maximum single position (%)').fill('25');
  await page.getByRole('button',{name:'Save policy'}).click();
  await page.locator('#toast').filter({hasText:'Risk policy saved'}).waitFor();
  await page.getByRole('button',{name:'Switch to Alpaca data'}).click();
  await page.locator('#footer-mode').filter({hasText:'ALPACA DATA'}).waitFor();
  await page.getByRole('button',{name:'Switch to simulation'}).click();
  await page.locator('#footer-mode').filter({hasText:'SIMULATION'}).waitFor();
  await page.locator('nav').getByRole('button',{name:'Overview'}).click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(artifactDir,'mobile.png'),fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'horizontal overflow');
  assert.deepEqual(errors,[]);
  console.log('PASS: dashboard, pipeline, search, event inspection, order fill, portfolio, pause, training, activation, settings, mode isolation, mobile; no JS errors.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
